// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcac_z6Owr_uQPzt32nZUvCc9-4ReG-00',
    appId: '1:279601952226:web:7573b52939c5670a0875bb',
    messagingSenderId: '279601952226',
    projectId: 'sign-language-eleven',
    authDomain: 'sign-language-eleven.firebaseapp.com',
    storageBucket: 'sign-language-eleven.firebasestorage.app',
    measurementId: 'G-SECW7LDQF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaafBFu2kbjDFo5dNC0HqOHhDlBG4KFv4',
    appId: '1:279601952226:android:47cd983788e448b90875bb',
    messagingSenderId: '279601952226',
    projectId: 'sign-language-eleven',
    storageBucket: 'sign-language-eleven.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBexKJyeQdy-kDVkmXZRve3tvJ6nhg7qZc',
    appId: '1:279601952226:ios:196b5657be5ab42a0875bb',
    messagingSenderId: '279601952226',
    projectId: 'sign-language-eleven',
    storageBucket: 'sign-language-eleven.firebasestorage.app',
    iosBundleId: 'com.eleven.vsl.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBexKJyeQdy-kDVkmXZRve3tvJ6nhg7qZc',
    appId: '1:279601952226:ios:196b5657be5ab42a0875bb',
    messagingSenderId: '279601952226',
    projectId: 'sign-language-eleven',
    storageBucket: 'sign-language-eleven.firebasestorage.app',
    iosBundleId: 'com.eleven.vsl.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcac_z6Owr_uQPzt32nZUvCc9-4ReG-00',
    appId: '1:279601952226:web:3f3128e3933b14a40875bb',
    messagingSenderId: '279601952226',
    projectId: 'sign-language-eleven',
    authDomain: 'sign-language-eleven.firebaseapp.com',
    storageBucket: 'sign-language-eleven.firebasestorage.app',
    measurementId: 'G-PE18ZPCXPF',
  );
}
